# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-09-13 09:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='farm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farm_id', models.CharField(max_length=20)),
                ('house_id', models.CharField(max_length=20)),
                ('farm_area', models.CharField(max_length=20)),
                ('season_crop', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Households',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Household_id', models.CharField(max_length=20)),
                ('Households_lat', models.CharField(max_length=20)),
                ('person_id', models.CharField(max_length=20)),
                ('person', models.CharField(max_length=20)),
                ('gender', models.CharField(max_length=20)),
                ('age', models.CharField(max_length=20)),
                ('person_hid', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='points',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points_id', models.CharField(max_length=20)),
                ('farm_id', models.CharField(max_length=20)),
                ('lat', models.CharField(max_length=20)),
                ('lon', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='village',
            fields=[
                ('village_id', models.AutoField(primary_key=True, serialize=False)),
                ('village_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='wateryield',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('well_id', models.CharField(max_length=20)),
                ('yieldd', models.CharField(max_length=20)),
                ('DateTimeField', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='well',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('well_id', models.CharField(max_length=20)),
                ('farm_id', models.CharField(max_length=20)),
                ('lat', models.CharField(max_length=20)),
                ('lon', models.CharField(max_length=20)),
            ],
        ),
    ]
