# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-09-13 09:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='village',
            old_name='village_id',
            new_name='id',
        ),
    ]
