# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-15 21:54
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapp', '0002_auto_20170915_2152'),
    ]

    operations = [
        migrations.CreateModel(
            name='dumb',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('farmm_id', models.CharField(max_length=20)),
                ('point', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
        ),
    ]
