# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-09-13 17:24
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapp', '0003_auto_20170913_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wateryield',
            name='DateTimeField',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
